/* Generated by cbindgen from src/capi.rs. Do not edit by hand. */

#ifndef RUST_ANALYZER_LSP_H
#define RUST_ANALYZER_LSP_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum RustAnalyzerStatus {
  RUST_ANALYZER_OK = 0,
  RUST_ANALYZER_INVALID_ARGUMENT = 1,
  RUST_ANALYZER_WORKSPACE_LOAD = 2,
  RUST_ANALYZER_ANALYSIS = 3,
  RUST_ANALYZER_TIMEOUT = 4,
  RUST_ANALYZER_CANCELLED = 5,
  RUST_ANALYZER_UNSUPPORTED = 6,
  RUST_ANALYZER_INTERNAL = 7,
} RustAnalyzerStatus;

typedef struct RustAnalyzerDefSite {
  const char *qualified_name;
  const char *rel_path;
  uint32_t start_line;
  uint32_t end_line;
} RustAnalyzerDefSite;

typedef struct RustAnalyzerCall {
  const char *callee_name;
  const char *enclosing_func_qn;
} RustAnalyzerCall;

typedef struct RustAnalyzerImport {
  const char *local_name;
  const char *module_path;
} RustAnalyzerImport;

typedef struct RustAnalyzerFile {
  const char *source;
  int source_len;
  const char *rel_path;
  const char *module_qn;
  const struct RustAnalyzerCall *calls;
  int call_count;
  const struct RustAnalyzerImport *imports;
  int import_count;
} RustAnalyzerFile;

typedef struct RustAnalyzerResolvedCall {
  const char *caller_qn;
  const char *callee_qn;
  const char *strategy;
  float confidence;
  const char *reason;
} RustAnalyzerResolvedCall;

typedef struct RustAnalyzerResolvedCallArray {
  struct RustAnalyzerResolvedCall *items;
  int count;
  int cap;
} RustAnalyzerResolvedCallArray;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

enum RustAnalyzerStatus rust_analyzer_resolve_batch(const char *workspace_root,
                                                    const struct RustAnalyzerDefSite *def_sites,
                                                    int def_site_count,
                                                    const struct RustAnalyzerFile *files,
                                                    int file_count,
                                                    struct RustAnalyzerResolvedCallArray *out);

void rust_analyzer_free_resolved_call_array(struct RustAnalyzerResolvedCallArray *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RUST_ANALYZER_LSP_H */
